<?xml version='1.0' encoding='iso-8859-1' standalone='no'?>
<!DOCTYPE issue SYSTEM "lwg-issue.dtd" [ 
  <!ENTITY nbsp "&#160;">
] >

<issue num="1004" status="WP">
<title>Response to UK 179</title>
<section><sref ref="[res.on.functions]"/></section>
<submitter>Alisdair Meredith</submitter>
<date>11 Mar 2009</date>

<discussion>

<p><b>Addresses UK 179</b></p>

<p>
According to the 4th bullet there is a problem if "if any replacement
function or handler function or destructor operation throws an
exception". There should be no problem throwing exceptions so long as
they are caught within the function.
</p>

<note>
Batavia (2009-05):
</note>
<blockquote><p>
The phrasing "throws an exception" is commonly used elsewhere
to mean "throws or propagates an exception."
Move to Open pending a possible more general resolution.
</p></blockquote>

<note>
2009-07 Frankfurt:
</note>

<blockquote><p>
Replace "propagates" in the proposed resolution with the phrase "exits
via" and move to Ready.
</p></blockquote>

</discussion>

<resolution>
<p>
Change the 4th bullet of <sref ref="[res.on.functions]"/>, p2:
</p>

<blockquote>
<ul>
<li>
if any replacement function or handler function or destructor operation
<del>throws</del> <ins>exits via</ins> an exception, unless specifically
allowed in the applicable <i>Required behavior:</i> paragraph.
</li>
</ul>
</blockquote>

</resolution>

</issue>
