<?xml version='1.0' encoding='iso-8859-1' standalone='no'?>
<!DOCTYPE issue SYSTEM "lwg-issue.dtd" [
  <!ENTITY nbsp "&#160;">
] >

<issue num="1506" status="NAD Editorial">
<title>[FCD] Ballot Comment US-198</title>
<section><sref ref="[futures.promise]"/></section>
<submitter>ANSI</submitter>
<date>25 Aug 2010</date>

<discussion>
<p><b>Addresses US-198</b></p>

promise::set_exception can be called with a null pointer,
but none of the descriptions of the get() functions for the
three types of futures say what happens for this case.

<note>
Resolved in Rapperswil by a motion to directly apply the words from the ballot comment in N3102.
</note>

</discussion>

<resolution>
Add the following sentence to the end of
30.6.5/22: The behavior of a program that calls
set_exception with a null pointer is undefined.
</resolution>

</issue>
